language: objective-c
 
script:
- xcodebuild build -scheme Authenticator -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6"
- xcodebuild build -scheme AuthenticatorExample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6"